#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libraries.Dynamics.DynamicsClient
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("v1_CreateContactWithAuth0")]
	public partial class V1_CreateContactWithAuth0Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Auth0Id = "Auth0Id";
			public const string Email = "Email";
			public const string Mobile = "Mobile";
		}
		
		public const string ActionLogicalName = "v1_CreateContactWithAuth0";
		
		public string Auth0Id
		{
			get
			{
				if (this.Parameters.Contains("auth0Id"))
				{
					return ((string)(this.Parameters["auth0Id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["auth0Id"] = value;
			}
		}
		
		public string Email
		{
			get
			{
				if (this.Parameters.Contains("email"))
				{
					return ((string)(this.Parameters["email"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["email"] = value;
			}
		}
		
		public string Mobile
		{
			get
			{
				if (this.Parameters.Contains("mobile"))
				{
					return ((string)(this.Parameters["mobile"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["mobile"] = value;
			}
		}
		
		public V1_CreateContactWithAuth0Request()
		{
			this.RequestName = "v1_CreateContactWithAuth0";
			this.Auth0Id = default(string);
			this.Email = default(string);
			this.Mobile = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("v1_CreateContactWithAuth0")]
	public partial class V1_CreateContactWithAuth0Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ContactId = "ContactId";
		}
		
		public const string ActionLogicalName = "v1_CreateContactWithAuth0";
		
		public V1_CreateContactWithAuth0Response()
		{
		}
		
		public System.Guid ContactId
		{
			get
			{
				if (this.Results.Contains("contactId"))
				{
					return ((System.Guid)(this.Results["contactId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["ContactId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
