#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libraries.Dynamics.DynamicsClient
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("v1_CreateContactWithAuth0")]
	public partial class v1_CreateContactWithAuth0Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string email = "email";
			public const string auth0Id = "auth0Id";
		}
		
		public const string ActionLogicalName = "v1_CreateContactWithAuth0";
		
		public string email
		{
			get
			{
				if (this.Parameters.Contains("email"))
				{
					return ((string)(this.Parameters["email"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["email"] = value;
			}
		}
		
		public string auth0Id
		{
			get
			{
				if (this.Parameters.Contains("auth0Id"))
				{
					return ((string)(this.Parameters["auth0Id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["auth0Id"] = value;
			}
		}
		
		public v1_CreateContactWithAuth0Request()
		{
			this.RequestName = "v1_CreateContactWithAuth0";
			this.email = default(string);
			this.auth0Id = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("v1_CreateContactWithAuth0")]
	public partial class v1_CreateContactWithAuth0Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string contactId = "contactId";
		}
		
		public const string ActionLogicalName = "v1_CreateContactWithAuth0";
		
		public v1_CreateContactWithAuth0Response()
		{
		}
		
		public System.Guid contactId
		{
			get
			{
				if (this.Results.Contains("contactId"))
				{
					return ((System.Guid)(this.Results["contactId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["contactId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
