name: Prepare Power Platform actions
description: Install Power Platform tools to enable Power Platform actions
runs:
  using: composite
  steps:
    - name: Install dot net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
