#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libraries.Dynamics.DynamicsClient
{
	
	
	/// <summary>
	/// Consent level for contact
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsGdPr_GdPr_Consent_Option_Set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(1) Consent", 0, "#0000ff")]
		_1Consent = 587030001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(2) Transactional", 1, "#0000ff")]
		_2Transactional = 587030002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(3) Subscriptions", 2, "#0000ff")]
		_3Subscriptions = 587030003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(4) Marketing", 3, "#0000ff")]
		_4Marketing = 587030004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(5) Profiling", 4, "#0000ff")]
		_5Profiling = 587030005,
	}
}
#pragma warning restore CS1591
