name: Build and push image(s) to Azure Container Registry
run-name: ${{ github.actor }} is running build and push image(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - .github/workflows/build-and-push.yaml
      - applications/**/*
      - libraries/**/*
  merge_group:
    types: [checks_requested]

jobs:
  get-applications-to-build:
    name: Get applications to build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    outputs:
      applications: ${{ steps.get-applications.outputs.applications }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🧰 Prepare monorepo tooling
        uses: ./.github/actions/prepare

      - name: 🔍 Get affected files
        uses: ./.github/actions/get-affected-files

      - name: 🏗️ Get applications to build
        id: get-applications
        run: |
          applications=$(pnpm nx show projects --json --affected --type app --exclude=auth0-post-login-trigger)
          echo "applications=$applications" >> $GITHUB_OUTPUT

  nothing-to-build:
    runs-on: ubuntu-latest
    name: Nothing to build
    needs: get-applications-to-build
    if: ${{ needs.get-applications-to-build.outputs.applications == '[]' ||  needs.get-applications-to-build.outputs.applications == '' }}
    steps:
      - name: Nothing to build
        run: |
          echo "# 🤷 Nothing to build" >>  $GITHUB_STEP_SUMMARY

  build-and-push:
    name: Build and push application
    runs-on: self-hosted-cdp
    needs: get-applications-to-build
    if: ${{ needs.get-applications-to-build.outputs.applications != '[]' && needs.get-applications-to-build.outputs.applications != '' }}
    strategy:
      fail-fast: true
      max-parallel: 3 # We have a limited number of runners
      matrix:
        application: ${{ fromJson(needs.get-applications-to-build.outputs.applications) }}
    env:
      DOTNET_INSTALL_DIR: './.dotnet'
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🧰 Prepare monorepo tooling
        uses: ./.github/actions/prepare

      - name: 🏗️ Build ${{ matrix.application }}
        run: pnpm nx build ${{ matrix.application }} --configuration=production

      - name: 📦 Build and push to Azure Container Registry
        uses: ./.github/actions/build-and-push
        env:
          SERVICE_PRINCIPAL: ${{ secrets.SERVICE_PRINCIPAL }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          ACR_TENANT_ID: ${{ secrets.ACR_TENANT_ID }}
          ACR_SUBSCRIPTION: ${{ secrets.ACR_SUBSCRIPTION }}
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          SELF_HOSTED_CDP_RUNNER_ROOT: ${{ vars.SELF_HOSTED_CDP_RUNNER_ROOT }}
        with:
          application: ${{ matrix.application }}
          version: $(git rev-parse --short ${{ github.sha }})

  prepare_releases:
    name: Prepare releases PRs, version bumps and changelogs
    runs-on: self-hosted-cdp
    needs: build-and-push
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🤖 Create GitHub application token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.DEPLOY_GITHUB_APP_ID }}
          private_key: ${{ secrets.DEPLOY_GITHUB_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        name: 🏷️ Prepare version bumps and changelogs
        with:
          token: ${{ steps.create_token.outputs.token }}
