name: Release and create a Git Tag
run-name: ${{ github.actor }} is running release and create a git tag
on:
  push:
    branches:
      - main
    paths:
      - applications/customerApi/version.txt
      - applications/nba/version.txt

jobs:
  release:
    name: Prepare releases PRs, version bumps and changelogs
    runs-on: self-hosted-cdp

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🤖 Create GitHub application token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.DEPLOY_GITHUB_APP_ID }}
          private_key: ${{ secrets.DEPLOY_GITHUB_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        name: 🏷️ Prepare version bumps and changelogs
        id: release
        with:
          token: ${{ steps.create_token.outputs.token }}

      - name: tag major and minor versions
        if: steps.release.outputs.releases_created == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/googleapis/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
